# see https://docs.github.com/en/github/administering-a-repository/customizing-dependency-updates
version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: daily
      open-pull-requests-limit: 20
      versioning-strategy: increase
      ignore:
          - dependency-name: 'golden-layout'
            # version 2 has too many breaking changes for now
            versions: ['2.x']
