version: '3.9'
services:
    mqtt:
        image: 'eclipse-mosquitto:1.6.10'
        restart: always
        ports:
            - '1883:1883'
        volumes:
            - ./mqtt/config:/mosquitto/config
            - ./mqtt/data:/mosquitto/data
            - ./mqtt/log:/mosquitto/log
    node-red:
        image: nodered/node-red:3.0.2
        restart: always
        environment:
            - TZ=Asia/Jerusalem
        ports:
            - '1880:1880'
        volumes:
            - ./node-red/data:/data
