version: '3.9'
services:
    node-red:
        image: nodered/node-red:3.0.2
        restart: always
        environment:
            - TZ=Asia/Jerusalem
        ports:
            - '1880:1880'
        volumes:
            - ./node-red/data:/data